apiVersion: node.k8s.io/v1
handler: "FILLED_BY_OPERATOR"
kind: RuntimeClass
metadata:
  labels:
    app.kubernetes.io/component: gpu-operator
  # Prevent helm from deleting the resource when removing the
  # runtime class from the k8s-platform-runtime-classes chart
  annotations:
    "helm.sh/resource-policy": keep
  name: "FILLED_BY_OPERATOR"
scheduling:
  nodeSelector:
    node-role.kubernetes.io/nodeless: ""
    node.datadoghq.com/runtime: nvidia
  tolerations:
    - effect: NoSchedule
      key: node
      value: nodeless
    - effect: NoSchedule
      key: runtime
      value: nvidia
    - effect: NoSchedule
      key: flavor
      value: nodeless-gpu
